baseURL = "http://mostlyoperational.com/"
languageCode = "en-us"
title = ""
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Pete Shima"
disqusShortname = "mostlyoperational-1"
googleAnalytics = "UA-27389150-1"

[params]
  logo = "/images/icon.png"
  description =""

[params.author]
  name = "Pete Shima"
  thumbnail = "/images/author.jpg"
  description = "Site Author"

[params.index]
  picture = "/images/quiteoperational.jpg"
  title = ""
  subtitle = "Ohh, I'm afraid the deflector shield will be quite operational."
  mdtext = '''**And the post incident review was epic.**'''
  alertbar = true

[params.social]
  github = "pshima"
  linkedin = "peteshima"
  twitter = "petey5k"


[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts"
[[menu.main]]
    name = "Slash"
    identifier = "about"
    weight = 200
    url = "/"